image: node:12.16.3

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - yarn install
    - yarn build

deploy:
  stage: deploy
  script:
    - cp -rv public/* /var/www/hello
  only:
    - master
